; CyberClean v2.2.3 -- Inno Setup Script
; AUTO-GENERATED by build.py -- chi sua version.py, roi chay: python build.py --inno
; Build: Open in Inno Setup Compiler -> Compile (F9)
; Download Inno Setup: https://jrsoftware.org/isinfo.php

[Setup]
AppName=CyberClean
AppVersion=2.2.3
AppPublisher=vuphitung
AppPublisherURL=https://github.com/vuphitung/CyberClean
AppSupportURL=https://github.com/vuphitung/CyberClean/issues
AppUpdatesURL=https://github.com/vuphitung/CyberClean/releases
DefaultDirName={autopf}\CyberClean
DefaultGroupName=CyberClean
AllowNoIcons=yes
OutputDir=dist
OutputBaseFilename=CyberClean_Setup_v2.2.3
SetupIconFile=assets\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; admin = UAC prompt khi install (1 lan duy nhat), app chay binh thuong sau do
PrivilegesRequired=admin
UninstallDisplayName=CyberClean
UninstallDisplayIcon={app}\CyberClean.exe
VersionInfoVersion=2.2.3.0
VersionInfoDescription=Smart Disk Cleaner
VersionInfoCompany=vuphitung
VersionInfoProductName=CyberClean

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
Source: "dist\CyberClean.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Shortcut truc tiep vao .exe -- khong dung schtasks
; schtasks /rl highest bi Defender danh dau la hanh vi nguy hiem -> app bi chan
Name: "{group}\CyberClean"; Filename: "{app}\CyberClean.exe"
Name: "{group}\Uninstall CyberClean"; Filename: "{uninstallexe}"
Name: "{userdesktop}\CyberClean"; Filename: "{app}\CyberClean.exe"; Tasks: desktopicon

[Run]
; Launch sau install -- Windows se hoi UAC 1 lan (binh thuong voi app can admin)
Filename: "{app}\CyberClean.exe"; Description: "Launch CyberClean"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\CyberClean"
Type: filesandordirs; Name: "{userappdata}\CyberClean"
