; CyberClean v2.2.3 — Inno Setup Script
; AUTO-GENERATED by build.py — do not edit VERSION here, edit version.py
; Build: Open in Inno Setup Compiler → Compile (F9)
; Download Inno Setup: https://jrsoftware.org/isinfo.php

[Setup]
AppName=CyberClean
AppVersion=2.2.3
AppPublisher=vuphitung
AppPublisherURL=https://github.com/vuphitung/CyberClean
AppSupportURL=https://github.com/vuphitung/CyberClean/issues
AppUpdatesURL=https://github.com/vuphitung/CyberClean/releases
DefaultDirName={autopf}\CyberClean
DefaultGroupName=CyberClean
AllowNoIcons=yes
OutputDir=dist
OutputBaseFilename=CyberClean_Setup_v2.2.3
SetupIconFile=assets\logo.ico
Compression=lzma
CloseApplications=yes
RestartApplications=no
AppMutex=CyberClean_Single_Instance_Lock
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName=CyberClean
UninstallDisplayIcon={app}\CyberClean.exe
VersionInfoVersion=2.2.3.0
VersionInfoDescription=Smart Disk Cleaner
VersionInfoCompany=vuphitung
VersionInfoProductName=CyberClean

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
Source: "dist\CyberClean.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Shortcut trực tiếp vào .exe — không dùng schtasks
; schtasks /rl highest dễ bị Defender/EDR đánh dấu hành vi đáng ngờ
Name: "{group}\CyberClean"; Filename: "{app}\CyberClean.exe"
Name: "{group}\Uninstall CyberClean"; Filename: "{uninstallexe}"
Name: "{userdesktop}\CyberClean"; Filename: "{app}\CyberClean.exe"; Tasks: desktopicon

[Run]
; Launch app sau khi cài xong
Filename: "{app}\CyberClean.exe"; Description: "Launch CyberClean"; Flags: nowait postinstall

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\CyberClean"
Type: filesandordirs; Name: "{userappdata}\CyberClean"
