# -*- mode: python ; coding: utf-8 -*-
# CyberClean — PyInstaller spec
# AUTO-GENERATED by build.py --inno / build.py --linux
# Nếu build bằng spec trực tiếp: pyinstaller CyberClean.spec
#
# FIX: icon path không còn hardcode absolute path (/home/tung/...)
#      → dùng relative path từ thư mục project
# FIX: version.py được bundle vào build (cần cho runtime version check)

import sys
from pathlib import Path

ROOT = Path(SPECPATH)   # SPECPATH = thư mục chứa .spec file

# Detect DLL (Windows only)
dll_path = ROOT / 'LibreHardwareMonitorLib.dll'
extra_datas = []
if dll_path.exists():
    extra_datas.append((str(dll_path), '.'))

a = Analysis(
    ['main.py'],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        ('version.py',    '.'),        # bundle version.py cho runtime import
        ('core/*.py',     'core'),
        ('utils/*.py',    'utils'),
        ('assets',        'assets'),
        *extra_datas,
    ],
    hiddenimports=[
        'psutil',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'clr',
        'clr._extra',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

# ── Icon: relative path, không hardcode ──────────────────
_ico = ROOT / 'assets' / 'logo.ico'
_png = ROOT / 'assets' / 'logo.png'

if sys.platform == 'win32':
    _icon = str(_ico) if _ico.exists() else None
else:
    _icon = str(_png) if _png.exists() else None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CyberClean',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CyberClean',
)
