; CyberClean v2.2.2 — Inno Setup Script
; AUTO-GENERATED by build.py — chỉ sửa version.py, rồi chạy: python build.py --inno
; Build: Open in Inno Setup Compiler → Compile (F9)
; Download Inno Setup: https://jrsoftware.org/isinfo.php

[Setup]
AppName=CyberClean
AppVersion=2.2.2
AppPublisher=vuphitung
AppPublisherURL=https://github.com/vuphitung/CyberClean
AppSupportURL=https://github.com/vuphitung/CyberClean/issues
AppUpdatesURL=https://github.com/vuphitung/CyberClean/releases
DefaultDirName={autopf}\CyberClean
DefaultGroupName=CyberClean
AllowNoIcons=yes
OutputDir=dist
OutputBaseFilename=CyberClean_Setup_v2.2.2
; FIX: relative path thay vì C:\CyberClean\assets\logo.ico (hardcode)
SetupIconFile=assets\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName=CyberClean
UninstallDisplayIcon={app}\CyberClean.exe
; FIX: VersionInfoVersion cần 4 số (Windows requirement): major.minor.patch.build
VersionInfoVersion=2.2.2.0
VersionInfoDescription=Smart Disk Cleaner
VersionInfoCompany=vuphitung
VersionInfoProductName=CyberClean

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
Source: "dist\CyberClean.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Shortcuts gọi schtasks để chạy Task ẩn — không bao giờ hiện UAC sau khi install
Name: "{group}\CyberClean"; Filename: "schtasks"; Parameters: "/run /tn ""CyberClean_AutoAdmin"""; IconFilename: "{app}\CyberClean.exe"
Name: "{group}\Uninstall CyberClean"; Filename: "{uninstallexe}"
Name: "{userdesktop}\CyberClean"; Filename: "schtasks"; Parameters: "/run /tn ""CyberClean_AutoAdmin"""; IconFilename: "{app}\CyberClean.exe"; Tasks: desktopicon

[Run]
; ONE-TIME UAC lúc install: tạo Scheduled Task với quyền highest
Filename: "schtasks"; Parameters: "/create /tn ""CyberClean_AutoAdmin"" /tr ""'{app}\CyberClean.exe'"" /sc onlogon /rl highest /f"; Flags: runhidden waituntilterminated
; Launch ngay sau install qua Task — không cần UAC
Filename: "schtasks"; Parameters: "/run /tn ""CyberClean_AutoAdmin"""; Description: "Launch CyberClean"; Flags: nowait postinstall skipifsilent runhidden

[UninstallRun]
; Xóa Task khi uninstall
Filename: "schtasks"; Parameters: "/delete /tn ""CyberClean_AutoAdmin"" /f"; Flags: runhidden waituntilterminated

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\CyberClean"
Type: filesandordirs; Name: "{userappdata}\CyberClean"
